### ISSUE TITLE
http proxy support

### ISSUE THREAD

**Issue by averzicco** [scalacenter/sbt-dependency-submission#144]
Hey, I'm trying to integrate this action in our workflow, but doesn't seem to work using an http proxy (direct internet access is not available).
I've added the sbt options:
```
SBT_OPTS="-Dhttp.proxyHost=hostname -Dhttp.proxyPort=port -Dhttps.proxyHost=hostname -Dhttps.proxyPort=port"
```
but it's ignored by the client, this is the error logged:

```
java.net.ConnectException: Connection timed out
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at gigahorse.shaded.apache.org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at gigahorse.shaded.apache.org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at gigahorse.shaded.apache.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at gigahorse.shaded.apache.org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
	at gigahorse.shaded.apache.org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I did some digging in the code and it seems that gigahorse apache http client doesn't support those options, so i did a quick test with asynchttpclient, which seems work fine.

do you have a specific reason why to use apache http client?
Would you accept a PR to switch the client to `asynchttpclient`

**Comment by averzicco** [comment]
I went ahead and created the PR
